# action.yml
name: 'Run java checkstyle'
description: 'Run java checkstyle with reviewdog'
inputs:
  github_token:
    description: 'GITHUB_TOKEN.'
    default: '${{ github.token }}'
  level:
    description: 'Report level for reviewdog [info,warning,error]'
    default: 'info'
  reporter:
    description: 'Reporter of reviewdog command [github-pr-check,github-pr-review]'
    default: 'github-pr-check'
  checkstyle_config:
    description: 'Checkstyle config file'
    required: true
    default: 'google_checks.xml'
runs:
  using: 'docker'
  image: 'Dockerfile'
